/// ----------------------------------------------------
///This code was generated by Lang CodeSmith
///Class:D_ItemTrend
///Copyright 2010(c) <Copyright>宇腾旅行网</Copyright> 
///Author     :<Author>周浪(zhoulanga)</Author>
///Date       :06/02/2017
///Description:会员的业务操作层
///对Table:ItemTrend的数据映射
///----------------------------------------------------
using System;
using System.Data;
using System.Text;
using System.Data.SqlClient;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace Silt.Client.Rules.Tao
{

    public class MAItemTrend : ZASuiteDAORulesQQ
    {

        public MAItemTrend()
        {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="FProducer_ID"></param>
        /// <returns></returns>
        public DataSet ByidDSWrite(string byID)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT * FROM ItemTrend Where ID='" + byID + "'";
            ds = this.DataSetLoadBySql(sql, "ItemTrend");
            return ds;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int ZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_ItemTrend_Insert";
            string strStoredProcDelete = "Y_ItemTrend_Delete";
            string strStoredProcUpdate = "Y_ItemTrend_Update";
            string strStrKey = "ID";
            string strStrTableName = "ItemTrend";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
    }
}