/// ----------------------------------------------------
///This code was generated by Lang CodeSmith
///Class:D_SrcFlow
///Copyright 2010(c) <Copyright>宇腾旅行网</Copyright> 
///Author     :<Author>周浪(zhoulanga)</Author>
///Date       :06/02/2017
///Description:会员的业务操作层
///对Table:SrcFlow的数据映射
///----------------------------------------------------
using System;
using System.Data;
using System.Text;
using System.Data.SqlClient;

using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace Silt.Client.Rules.Tao
{

    public class MASrcFlow : ZASuiteDAORulesQQ
    {

        public MASrcFlow()
        {
        }
        /// <summary>
        /// 30天曲线图
        /// </summary>
        /// <param name="ItemID"></param>
        /// <param name="PageName"></param>
        /// <param name="TypeID"></param>
        /// <returns></returns>
        public DataTable GetPage(string ItemID, string PageName, int TypeID)
        {
            string Sql = "SELECT  pv,uv,getdatedey FROM SrcFlow where ItemID='"+ ItemID + "' and pageName='"+ PageName + "' and typeID=1 order by getdatedey asc";
            return this.DataSetExecuteBySql(Sql).Tables[0];
        }
        public DataTable Getcombox()
        {
            string Sql = "SELECT DISTINCT ItemID,shopID  FROM SrcFlow order by shopID Desc";
            return this.DataSetExecuteBySql(Sql).Tables[0];
        }
        public DataTable GetPageName()
        {
            string Sql = "SELECT DISTINCT pageName  FROM SrcFlow order by pageName Desc";
            return this.DataSetExecuteBySql(Sql).Tables[0];
        }
        public void delFromItemID(string ItemID)
        {
            //每日成交关建字订单
            this.ExecuteNonQuery("delete  FROM[OrKeyword] where ItemID = '"+ ItemID + "'");
            //每日成交关建字流量
            this.ExecuteNonQuery("delete FROM [SeKeyword] where ItemID='"+ ItemID + "'");
            //每日前10流量榜
            this.ExecuteNonQuery("delete FROM  [SrcFlow] where ItemID='"+ ItemID + "'");
        }
        public DataSet OrderKeyByidDSWrite(string ItemID)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT top 3 * FROM View_Keyorder ";
            if (ItemID != "0")
            { sql = "SELECT * FROM View_Keyorder Where ItemID='" + ItemID + "' "; }
            ds = this.DataSetLoadBySql(sql, "View_Keyorder");
            return ds;
        }
        public DataSet ItemByidDSWrite(string ItemID)
        {
            //string sql = "SELECT top 10 * FROM SrcFlow ";
            //if (ItemID != "0")
            //{ sql = "SELECT top 10 * FROM SrcFlow ItemID='" + ItemID + "' "; }

            DataSet ds = new DataSet();
            string sql = "SELECT top 3 * FROM ItemTrend ";
           // string sql = "SELECT * FROM View_Keyorder ";
            if (ItemID != "0")
            { sql = "SELECT * FROM ItemTrend Where ItemID='" + ItemID + "' "; }
            ds = this.DataSetLoadBySql(sql, "ItemTrend");
            return ds;
        }
       /// <summary>
       /// PC无线TOP10成交
       /// </summary>
       /// <param name="byID"></param>
       /// <returns></returns>
        public DataSet OrderByidDSWrite(string ItemID)
        {
            string sql = "SELECT top 10 * FROM OrKeyword";
            if (ItemID != "0")
            { sql = "SELECT * FROM OrKeyword Where ItemID='" + ItemID + "' "; }
            DataSet ds = new DataSet();
          //  string sql = "SELECT * FROM OrKeyword Where ID=" + byID + "";
            ds = this.DataSetLoadBySql(sql, "OrKeyword");
            return ds;
        }

        public DataSet CMKeyByidDSWrite(string ItemID)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT top 10 * FROM CMKeyword ";
            if (ItemID != "")
            {
                sql = "SELECT * FROM CMKeyword Where ID='" + ItemID + "'";
            }
            ds = this.DataSetLoadBySql(sql, "CMKeyword");
            return ds;
        }

        public DataSet CMKeyByidDSWriteview(string ItemID)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT top 10 * FROM View_CMKeyword ";
            if (ItemID != "")
            {
                sql = "SELECT * FROM View_CMKeyword Where itemid='" + ItemID + "'";
            }
            ds = this.DataSetLoadBySql(sql, "CMKeyword");
            return ds;
        }
        /// <summary>
        /// 商家关建词分析
        /// </summary>
        /// <param name="byID"></param>
        /// <returns></returns>
        public DataSet shopkeyByidDSWrite(string ItemID)
        {
            string sql = "SELECT top 10 * FROM shopkeyword";
            if (ItemID != "0")
            { sql = "SELECT * FROM shopkeyword Where ItemID='" + ItemID + "' "; }
            DataSet ds = new DataSet();
            //  string sql = "SELECT * FROM OrKeyword Where ID=" + byID + "";
            ds = this.DataSetLoadBySql(sql, "shopkeyword");
            return ds;
        }

        /// <summary>
        /// 竞品关键词对比
        /// </summary>
        /// <param name="byID"></param>
        /// <returns></returns>
        public DataSet shopItembyID(string keydate,string Aitem,string ItemID)
        {
           
            string sql = "SELECT * FROM view_shuaKey Where AItemID='" + Aitem + "'And ItemID='"+ ItemID + "'And  keydate ='"+ keydate + "'"; 
            DataSet ds = new DataSet();
            //  string sql = "SELECT * FROM OrKeyword Where ID=" + byID + "";
            ds = this.DataSetLoadBySql(sql, "view_shuaKey");
            return ds;
        }
        /// <summary>
        /// TOP10无线PC关建词
        /// </summary>
        /// <param name="byID"></param>
        /// <returns></returns>
        public DataSet KeyByidDSWrite(string  ItemID)
        {
            string sql = "SELECT * FROM SeKeyword";
            if (ItemID != "0")
            { sql = "SELECT * FROM SeKeyword Where ItemID='" + ItemID + "' "; }

            DataSet ds = new DataSet();
           // string sql = "SELECT * FROM SeKeyword Where ItemID='"+ ItemID + "'";
            ds = this.DataSetLoadBySql(sql, "SeKeyword");
            return ds;
        }
        /// <summary>
        /// TOP10无线PC来源
        /// </summary>
        /// <param name="ItemID">宝贝ID</param>
        /// <returns></returns>
        public DataSet ByidDSWrite(string ItemID)
        {
            string sql = "SELECT top 10 * FROM SrcFlow ";          
            if (ItemID != "0")
            { sql = "SELECT  * FROM SrcFlow where ItemID='" + ItemID + "' "; }

            DataSet ds = new DataSet();
            ds = this.DataSetLoadBySql(sql, "SrcFlow");
            return ds;
        }/// <summary>
        /// 图表
        /// </summary>
        /// <param name="ItemID">宝贝ID</param>
        /// <returns></returns>
        public DataSet ItemTrendByidDSWrite(string ItemID)
        {
            string sql = "SELECT top 10 * FROM ItemTrend ";
            if (ItemID != "0")
            { sql = "SELECT * FROM ItemTrend ItemID='" + ItemID + "' "; }
            DataSet ds = new DataSet();
            ds = this.DataSetLoadBySql(sql, "ItemTrend");
            return ds;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int ZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_SrcFlow_Insert";
            string strStoredProcDelete = "Y_SrcFlow_Delete";
            string strStoredProcUpdate = "Y_SrcFlow_Update";
            string strStrKey = "ID";
            string strStrTableName = "SrcFlow";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
      
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int ItemTrendZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_ItemTrend_Insert";
            string strStoredProcDelete = "Y_ItemTrend_Delete";
            string strStoredProcUpdate = "Y_ItemTrend_Update";
            string strStrKey = "ID";
            string strStrTableName = "ItemTrend";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
       
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int KeyZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_SeKeyword_Insert";
            string strStoredProcDelete = "Y_SeKeyword_Delete";
            string strStoredProcUpdate = "Y_SeKeyword_Update";
            string strStrKey = "ID";
            string strStrTableName = "SeKeyword";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
      
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int OrderZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_OrKeyword_Insert";
            string strStoredProcDelete = "Y_OrKeyword_Delete";
            string strStoredProcUpdate = "Y_OrKeyword_Update";
            string strStrKey = "ID";
            string strStrTableName = "OrKeyword";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }

        public int ShopkeywordZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_shopkeyword_Insert";
            string strStoredProcDelete = "Y_shopkeyword_Delete";
            string strStoredProcUpdate = "Y_shopkeyword_Update";
            string strStrKey = "ID";
            string strStrTableName = "shopkeyword";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
        /// <summary>
        /// 流量解析过程
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int JXkeywordZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_JxKeyword_Insert";
            string strStoredProcDelete = "Y_JxKeyword_Delete";
            string strStoredProcUpdate = "Y_JxKeyword_Update";
            string strStrKey = "ID";
            string strStrTableName = "JxKeyword";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }

        /// <summary>
        /// 生意参谋手淘搜索
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int SYSTUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_CMKeyword_Insert";
            string strStoredProcDelete = "Y_CMKeyword_Delete";
            string strStoredProcUpdate = "Y_CMKeyword_Update";
            string strStrKey = "ID";
            string strStrTableName = "CMKeyword";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
    }
}