/// ----------------------------------------------------
///This code was generated by Lang CodeSmith
///Class:D_QQ_List
///Copyright 2008(c) <Copyright>芷恋</Copyright> 
///Author     :<Author>周浪(zhoulanga)</Author>
///Date       :05/11/2017
///Description:直通车
///对Table:QQ_List的数据映射
///----------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;


namespace Silt.Client.Rules.QQList
{

    public class DCQQ_List : ZASuiteDAORulesQQ
    {
        
        public DCQQ_List()
        {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="FProducer_ID"></param>
        /// <returns></returns>
        public DataSet ByidDSWrite(string byID)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT * FROM QQ_List Where QQID='" + byID + "'";
            ds = this.DataSetLoadBySql(sql, "QQ_List");
            return ds;
        }
        public DataSet ByidDSWrite()
        {
            DataSet ds = new DataSet();
            string sql = "SELECT * FROM QQ_List";
            ds = this.DataSetLoadBySql(sql, "QQ_List");
            return ds;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int ZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_QQ_List_Insert";
            string strStoredProcDelete = "Y_QQ_List_Delete";
            string strStoredProcUpdate = "Y_QQ_List_Update";
            string strStrKey = "QQID";
            string strStrTableName = "QQ_List";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
    }
}