/// ----------------------------------------------------
///This code was generated by Lang CodeSmith
///Class:D_QQ_Txt
///Copyright 2008(c) <Copyright>芷恋</Copyright> 
///Author     :<Author>周浪(zhoulanga)</Author>
///Date       :05/11/2017
///Description:直通车
///对Table:QQ_Txt的数据映射
///----------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;


namespace Silt.Client.Rules.QQList
{

    public class DCQQ_Txt : ZASuiteDAORulesQQ
    {
      //  private Silt.Client.Rules.ZASuiteDAORulesSys rulesSys = new Silt.Client.Rules.ZASuiteDAORulesSys();
        public DCQQ_Txt()
        {
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="FProducer_ID"></param>
        /// <returns></returns>
        public DataSet ByidDSWrite(string byID)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT * FROM QQ_Txt Where txtID='" + byID + "'";
            ds = this.DataSetLoadBySql(sql, "QQ_Txt");
            return ds;
        }

        public DataSet SelectDSWrite(string Sql)
        {
            DataSet ds = new DataSet();
            string sql = "SELECT * FROM QQ_Txt "+ Sql;
            ds = this.DataSetLoadBySql(sql, "QQ_Txt");
            return ds;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dsObject"></param>
        /// <returns></returns>
        public int ZAUpdate(DataSet dsObject)
        {
            string strStoredProcAdd = "Y_QQ_Txt_Insert";
            string strStoredProcDelete = "Y_QQ_Txt_Delete";
            string strStoredProcUpdate = "Y_QQ_Txt_Update";
            string strStrKey = "txtID";
            string strStrTableName = "QQ_Txt";
            return this.DataSetUpdate(dsObject, strStrTableName, strStrKey, strStoredProcAdd, strStoredProcDelete, strStoredProcUpdate);
        }
    }
}