/// ----------------------------------------------------
///This code was generated by Lang CodeSmith
///Class:D_YT_Blank
///Copyright 2008(c) <Copyright>宇腾旅行网</Copyright> 
///Author     :<Author>周浪(zhoulanga)</Author>
///Date       :05-14-2009
///Description:会员的业务操作层
///对Table:YT_Blank的数据映射
///----------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Silt.Client.Rules
{
    public class ZASuiteDAORulesQQ : Silt.Client.Rules.ZASuiteDAORules
    {
        public ZASuiteDAORulesQQ()
        {
            this.ZAStrConn = "Silt.DBConn.SqlServer.QQ";
        }
    }
}